const galeryProyects = [
  {
    ID: "1",
    PROYECTO: "Gus espada",
    TITULO: "Plataforma de suscripción de cursos y arreglos corales",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Gustavo Espada",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2020",
    TAG: "",
    CATEGORIA: "eCommerce Plataforma",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://gusespada.com/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Gus_espada.png",
  },
  {
    ID: "2",
    PROYECTO: "Logitrader",
    TITULO: "Plataforma de soluciones logísticas",
    SOBRE:
      "Una empresa ubicada en Miami, quería comunicar a sus potenciales clientes la trayectoria y las soluciones de logisticas que ofrecen al rededor del munodo. Diseñamos una web a medida haciendo focos en los sedrvicios principales, haciendo foco en las seccione de contacto para que se puedan poner en contacto fácil con la empresa, tambien desarrollamos un formulario inteligente que sirve a la empresa como un filtro para cotizar sus servicios. Sitio con (A11) accesiilidad para personas con discapacidad.",
    RURO: "Empresa de logistica",
    CLIENTE: "Marcas y Mercados",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE:
      "Diseño web con accesibilidad para personas con discapaidad. ",
    AÑO: "2021",
    TAG: "#UX UI Costomizadas #HTML5 #Bootstrap",
    CATEGORIA: "Institucional",
    WEB: "Si",
    MOBILE: "Si",
    MOCK: "Listo",
    PRIORIDAD: "Alta",
    LINK: "No funciona",
    TAG_MOCK: "Empresarial",
    PAIS: "Estados Unidos",
    IMG_SRC: "Logiter.png",
  },
  {
    ID: "3",
    PROYECTO: "Linetec",
    TITULO: "Soluciones técnologicas - Web Institucional ",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2020",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://linetec.com.ar/",
    TAG_MOCK: "",
    PAIS: "Argentina",
    IMG_SRC: "Linetec.png",
  },
  {
    ID: "4",
    PROYECTO: "Taller",
    TITULO: "Sitio web de software, innovación y tecnología",
    SOBRE:
      "Taller es una empresa de tecnologia  Alemania, al momento de contratarnos estaban apsando por un momento expación, y particpando de rondas de ibversión. Necesitaban una web que comunique innovación, experieencia, y tecnologia para generfar un status frente a sus potenciale sinversiones. Desarrollamos una web minimalista. con un diseño funcional al público objetivo, y con un diseño exclusivo mobile. ",
    RURO: "Empresa de Software",
    CLIENTE: "Taller",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2020",
    TAG: "#UX UI Costomizadas #HTML5 #Bootstrap",
    CATEGORIA: "Institucional",
    WEB: "Si",
    MOBILE: "Si",
    MOCK: "Listo",
    PRIORIDAD: "Alta",
    LINK: "No funciona",
    TAG_MOCK: "",
    PAIS: "Alemania",
    IMG_SRC: "Taller.png",
  },
  {
    ID: "5",
    PROYECTO: "Pablo Lavezzari",
    TITULO: "Sitio web de exposición de obras artísticas",
    SOBRE:
      "Pablo Lavezari es un artista córdobes. El desafío que nos planteó Cinergia fue montar una plataforma donde se puedan lucir las obras del artistas y estas causen un impacto visual al usaurio al momento de ingresar a la web. Desarrollamos un sitio enfocado en lo visual, un sitio que genera un interés e interpela al usuario que ingresa al sitio, genera curiosidad de conocer más sobre el airtista. El sitio está capacitado para coneter muchos videos y fotos y funcioar bien, también cuenta con un blog y un portfolio de proyectos auto administrable. \nLa web tiene un Premio Fepi 2021",
    RURO: "",
    CLIENTE: "Cinergia Estudio Creativo",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2021",
    TAG: "#Wordpress #UX #UI",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Alta",
    LINK: "https://pablolavezzari.com/",
    TAG_MOCK: "",
    PAIS: "Argentina",
    IMG_SRC: "Pablo_Lavezzari.png",
  },
  {
    ID: "6",
    PROYECTO: "Del Gredal",
    TITULO: "Bodega: historia y productos",
    SOBRE:
      "Del Gredal es una bodega en pleno Cerro Colorado de la pcia de Córdoba, ubicando sobre el antiguo camino real. Es una bodega con historia, eso es lo que quisieron trasmitir en el sitio web. El desafio de Cinergia fue plasmar el nuevo Branding de la marca y contar su historia en la web. Diseñamos una web institucional donde plasmamos el espiritu de la marca, sus colores, tipografias de modo tal que fue un éxito y obtuvo un premio Eikon 2021. El sitio cuenta con secciones donde se muestra la historia de la marca, se hizo incapie en los vinos, en cada variedad y en su proceso. ",
    RURO: "Bodega",
    CLIENTE: "Cinergia Estudio Creativo",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2021",
    TAG: "#Wordpress #Blog ",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Alta",
    LINK: "https://delgredal.com/",
    TAG_MOCK: "",
    PAIS: "Argentina",
    IMG_SRC: "Gardel_vino.png",
  },
  {
    ID: "7",
    PROYECTO: "ICES",
    TITULO: "Plataforma de eLearning",
    SOBRE: "",
    RURO: "",
    CLIENTE: "ICES",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2021",
    TAG: "",
    CATEGORIA: "Institucional eCommerce Plataforma",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://icesweb.org/",
    TAG_MOCK: "",
    PAIS: "Argentina",
    IMG_SRC: "ICES.png",
  },
  {
    ID: "8",
    PROYECTO: "FUCA",
    TITULO: "Fundación de arte ",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Di Cuore",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2021",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media - Baja",
    LINK: "https://fucaarte.org/",
    TAG_MOCK: "",
    PAIS: "Argentina",
    IMG_SRC: "Fuca.png",
  },
  {
    ID: "9",
    PROYECTO: "FF",
    TITULO: "Plataforma de gestión de ciudadanos ",
    SOBRE: "",
    RURO: "",
    CLIENTE: "MCDG",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2021",
    TAG: "",
    CATEGORIA: "Plataforma",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://centrofamiliarvirtual.fundaciondelasfamilias.cl/",
    TAG_MOCK: "",
    PAIS: "Chile",
    IMG_SRC: "Fundacion_familias.png",
  },
  {
    ID: "10",
    PROYECTO: "AQUA",
    TITULO: "Tecnologia agropecuaria",
    SOBRE: "",
    RURO: "",
    CLIENTE: "MCDG",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2021",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media ",
    LINK: "https://aqua.capital/",
    TAG_MOCK: "#Wordpress #UI Personalizado #Blog",
    PAIS: "Brasil",
    IMG_SRC: "Aqua_capital.png",
  },
  {
    ID: "11",
    PROYECTO: "Bienal",
    TITULO: "Galeria de Arte",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Di Cuore",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2021",
    TAG: "",
    CATEGORIA: "Plataforma",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://bienal.fucaarte.org/",
    TAG_MOCK: "#Wordpress #UI Personalizado #Blog",
    PAIS: "",
    IMG_SRC: "Bienal.png",
  },
  {
    ID: "12",
    PROYECTO: "Aeromas",
    TITULO: "Vuelos en Jet privados",
    SOBRE: "",
    RURO: "",
    CLIENTE: "22DG",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2022",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://aeromas.com/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "",
  },
  {
    ID: "13",
    PROYECTO: "Aeromas back",
    TITULO: "",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2022",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "Falta",
    PRIORIDAD: "Media - Baja",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "aeromas_back.png",
  },
  {
    ID: "14",
    PROYECTO: "Esa",
    TITULO: "Agencia de Marketing Digital",
    SOBRE: "",
    RURO: "",
    CLIENTE: "ESA",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2020",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://www.marketingesa.com/",
    TAG_MOCK: "#Onepage #Wordpress",
    PAIS: "",
    IMG_SRC: "esa.png",
  },
  {
    ID: "15",
    PROYECTO: "Marian",
    TITULO: "Consultora de Marcas",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Marian",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2021",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://www.marianpd.com/",
    TAG_MOCK: "#Custom #Bootstrap #Admin",
    PAIS: "",
    IMG_SRC: "MArian_pd.png",
  },
  {
    ID: "16",
    PROYECTO: "Tres 51",
    TITULO: "Empresa de Retail",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Tres 51",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2021",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja",
    LINK: "https://tres51.com/",
    TAG_MOCK: "#Bootstrap #Multidioma",
    PAIS: "",
    IMG_SRC: "Tres_51.png",
  },
  {
    ID: "17",
    PROYECTO: "Efitech",
    TITULO: "Empresa de Tecnología para la ganadería",
    SOBRE:
      "Una empresa de Softaeare para el agro necesitaba el diseño de un sitio web para comunicar y vender todos sus servivios. El desarrollo de la página web cuenta una experiencia de usaurio personalizada para guiar al usuario al contacto. Un blog con todas las ultimas novedades",
    RURO: "Agro",
    CLIENTE: "Villa Nueva",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2020",
    TAG: "#UX #UI #Wordpress #Blog ",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Alta",
    LINK: "https://efitech.villanueva.com.ar/",
    TAG_MOCK: "#Wordpress #Blog #Diseño UI personalizado",
    PAIS: "",
    IMG_SRC: "Efitech.png",
  },
  {
    ID: "18",
    PROYECTO: "Grow",
    TITULO: "Hay que hacer mock",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "Falta",
    PRIORIDAD: "Media",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Grow.png",
  },
  {
    ID: "19",
    PROYECTO: "Prontophot",
    TITULO: "Tienda de fotos",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Prontophot",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2020",
    TAG: "",
    CATEGORIA: "eCommerce",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://prontophot.com/",
    TAG_MOCK: "#Bootstrap #Admin",
    PAIS: "",
    IMG_SRC: "Pronto.png",
  },
  {
    ID: "20",
    PROYECTO: "Xpress Rendering",
    TITULO: "Agencia de renders",
    SOBRE:
      "Empresa de Florida que realizada Renders a todo el mundo. Utiliza la web para mostrar sus trabajos y generar leads\nXpress rendering, nos contrató ara rediseñar el sitio, querian un sitio moderno a la altura de la competenica, que comunique el nivel de empresa, y sobre todo querian mostrar la amplia gama de servicios que ofrecen. \nCreamos una web con un diseño sofisticado, con una experiencia de usaurio que guía al visitante por todos los servicios que la empresa ofrece. La web cuenta con un blog autoadministable.",
    RURO: "Arquitectura",
    CLIENTE: "Xpress Rendering",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2020",
    TAG: "#Wordpress #UX #UI #Customizada #Portfolio #Blog",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Alta",
    LINK: "https://xpressrendering.com/",
    TAG_MOCK: "#Wordpress #Diseño personalizado",
    PAIS: "Estados Unidos",
    IMG_SRC: "XpressR.png",
  },
  {
    ID: " ",
    PROYECTO: "Venturi",
    TITULO: "Empresa de respuestos hidráulicos ",
    SOBRE:
      "Empresa de Córdoba al mundo, unica en latinoamerica en la fabricación Olehidraulica. Utilizan la web para abrir nuevos mercados y como posicioanamiento. La web tiene un Buscador inteligente de productos \nUna empresa familiar de muchos años, querian renovarse y tener un sitio actualizado. Necesitaban mostrar sus productosl, y que los usuairos encuentren rápido el producto que buscan. Hicimos un buscador inteligente. La web está en 3idiomas ",
    RURO: "Fabrica",
    CLIENTE: "Venturi Hnos. SA",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2019",
    TAG: "#Bostratp #Laravel ",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Alta",
    LINK: "https://www.venturi.com.ar/",
    TAG_MOCK: "",
    PAIS: "Argentina",
    IMG_SRC: "venturi.png",
  },
  {
    ID: " ",
    PROYECTO: "Tribunal de cuentas",
    TITULO: "Plataforma de gestión de trámites y consultas",
    SOBRE:
      "Tribunal de cuentas de la pcia de córdoba. Tenian la necesidad de general una plataforma dónde la comunidad pueda ser guiada facilmente a los tramites y consultas frecuentes",
    RURO: "Gobierno",
    CLIENTE: "Tribunal de cuentas",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2019",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Alta",
    LINK: "https://www.tcpcordoba.gov.ar/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Tribunales_de_cuentas.png",
  },
  {
    ID: "23",
    PROYECTO: "Bicis",
    TITULO: "Congreso intenacional de bicis ",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Guillermo Liverotti",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://combici.org/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Bicis.png",
  },
  {
    ID: "24",
    PROYECTO: "ECO",
    TITULO: "Fundación de reciclaje ",
    SOBRE: "",
    RURO: "",
    CLIENTE: "ECO Inclusión",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2020",
    TAG: "",
    CATEGORIA: "Institucional eCommerce",
    WEB: "",
    MOBILE: "",
    MOCK: "Nuevo mock",
    PRIORIDAD: "Media",
    LINK: "",
    TAG_MOCK: "#Bootstrap #Admin #Pagos #Multidioma #Multimoneda",
    PAIS: "",
    IMG_SRC: "ecoinclusion.png",
  },
  {
    ID: "25",
    PROYECTO: "Librematica",
    TITULO: "No funciona. ver de levantar",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2019",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Librematica.png",
  },
  {
    ID: "26",
    PROYECTO: "Franco Fit",
    TITULO: "No funciona",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2019",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Franco_fitt.png",
  },
  {
    ID: "27",
    PROYECTO: "Ralseff",
    TITULO: "Venta de cursos",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Ralseff",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2018",
    TAG: "",
    CATEGORIA: "Landing",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://ralseff.com/cursosecretariado/",
    TAG_MOCK: "#Onepage",
    PAIS: "",
    IMG_SRC: "Ralseff.png",
  },
  {
    ID: "28",
    PROYECTO: "Wallace",
    TITULO: "No funciona",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2018",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "Falta",
    PRIORIDAD: "Media - Baja",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Wallace.png",
  },
  {
    ID: "29",
    PROYECTO: "Aprovit",
    TITULO: "Empresa de comunicaciones ",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2018",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://www.approve-itsa.com/",
    TAG_MOCK: "#Multidioma #Bootstrap #Admin ",
    PAIS: "Estados Unidos",
    IMG_SRC: "Approve-it.png",
  },
  {
    ID: "30",
    PROYECTO: "Yo mamá",
    TITULO: "No funciona",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Landing",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "yomama.png",
  },
  {
    ID: "31",
    PROYECTO: "America gis",
    TITULO: "No funciona",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "americagis.png",
  },
  {
    ID: "32",
    PROYECTO: "JM Grop",
    TITULO: "Plataforma de alquiler de departamentos temporrarios en Brasil ",
    SOBRE:
      "Empresa que alquila departamentos temporrarios en Brasil. Multiidioma y multidivisa. Tiene un admiistrador para gestionar los departamentos, agregar fotos, precios. Y se puede poner un solo precio en dolar y el sistema calcula el precio dependiendo la moneda. Se pueden hacer las reservas y pagos por la misma plataforma. Es un eCommerce alquiler y reserva de departamentos",
    RURO: "",
    CLIENTE: "El Lapiz",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2018",
    TAG: "",
    CATEGORIA: "Institucional Plataforma",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Alta",
    LINK: "https://groupjm.com/",
    TAG_MOCK: "#Multidioma #Multimoneda #Pagos #eComerce #Admin",
    PAIS: "",
    IMG_SRC: "JM_group.png",
  },
  {
    ID: "33",
    PROYECTO: "Cognition",
    TITULO: "Inteligencia de neocios",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2020",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://cognitionbi.com/",
    TAG_MOCK: "#Onepage #Bootstrap",
    PAIS: "",
    IMG_SRC: "Cognition.png",
  },
  {
    ID: "34",
    PROYECTO: "Incesped",
    TITULO: "Cesped para chanchas ",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Incesped",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2018",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://incesped.com/",
    TAG_MOCK: "#Bootstrap #Diseño personalizado",
    PAIS: "",
    IMG_SRC: "Incesped.png",
  },
  {
    ID: "35",
    PROYECTO: "Clinica Santa lucia",
    TITULO: "Clínica de ojos ",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Santa Lucia ",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2019",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja",
    LINK: "https://clinicasantaluciasalta.com/",
    TAG_MOCK: "#Bootstrap #Diseño personalizado",
    PAIS: "",
    IMG_SRC: "Clinica_santa_lucia.png",
  },
  {
    ID: "36",
    PROYECTO: "Craneo",
    TITULO: "Empresa de Software",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2018",
    TAG: "",
    CATEGORIA: "One-Page",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://craneo.io/",
    TAG_MOCK: "#Bootstrap #Diseño personalizado",
    PAIS: "",
    IMG_SRC: "Craneo.png",
  },
  {
    ID: "37",
    PROYECTO: "Flug",
    TITULO: "No funciona",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "flug.png",
  },
  {
    ID: "38",
    PROYECTO: "Renta auto",
    TITULO: "Renta de autos",
    SOBRE:
      "Necesitaban una web que sea accesible en diferentesidiomas y monedas por el publico. Diseñamos una web minimalista y fácil de navegar. Empresa de alquiler/rentas de autos en toda argentina. El usuario puede alquilar un auto en una ciudad y devolver en otra. El sistema contembla un administrador donde pueden gestionar los autos, precios, puntos de retiro y devolución. Y hacer las reservas pagando por la plataforma.",
    RURO: "",
    CLIENTE: "Inglobe",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2017",
    TAG: "",
    CATEGORIA: "Plataforma Institucional eCommerce",
    WEB: "",
    MOBILE: "",
    MOCK: "Nuevo mok",
    PRIORIDAD: "Alta",
    LINK: "https://www.rentautoargentina.com.ar/",
    TAG_MOCK: "#ecommerce #Laravel ",
    PAIS: "",
    IMG_SRC: "Rentauto.png",
  },
  {
    ID: "39",
    PROYECTO: "Ralseff",
    TITULO: "Plataforma integral para cursos online: gestión de pagos y clases",
    SOBRE:
      "Instituto educativo que vende cursos cortos. En la plataforma el usuario puede inscribirse al curso, pagar y realizar los cursos por el mismo. Tiene un sistema de cobros por cuotas de financiación propia, el alumno entra y va generando sus pagos mes a mes. Tambien pueden hacer autoevaluaciones por el sistema y generar certificados. El alumno puede ver videos y descaragar material de estudio. El administrador de la plataforma puede crear curso, modulos y subir todo el contenido de cada clase. Hacer un seguimiento de los cobros y los pendientes a pagar. El sistema tiene una API personalizada desarrollada para integrar con mercado pago y que las trasacciones sean trasparentes. Tambien hay un función de que lo alumnos una vez terminado el curso puedan subir sus CV. Este sistema de CV se vende el accesos a responsable de rescursos humanos de empresas, hay dos accesos empresas y postulantes, funciona como una bolsa de trabajo.",
    RURO: "Educación",
    CLIENTE: "Ralseff",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2017",
    TAG: "",
    CATEGORIA: "Plataforma Institucional",
    WEB: " ",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Alta",
    LINK: "https://ralseff.com/",
    TAG_MOCK: "#eLearning #eCoomerce #Pagos #Admin #Laravel #Bootstrap",
    PAIS: "Argentina",
    IMG_SRC: "Ralseff.png",
  },
  {
    ID: "40",
    PROYECTO: "IEDES",
    TITULO: "Fundación júrdica y económica ",
    SOBRE: "",
    RURO: "",
    CLIENTE: "El Lapiz",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2019",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://institutoiedes.org/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "IEDES.png",
  },
  {
    ID: "41",
    PROYECTO: "Mterra",
    TITULO: "Empresa Desarrollista",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Grupo Miterra",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2017",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja",
    LINK: "https://grupomiterra.com/",
    TAG_MOCK: "#Wordpress",
    PAIS: "",
    IMG_SRC: "",
  },
  {
    ID: "42",
    PROYECTO: "La cuesta",
    TITULO: "Venta de lotes ",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Grupo Miterra",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2018",
    TAG: "",
    CATEGORIA: "Landing",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://lacuestavr.com.ar/",
    TAG_MOCK: "#Bootstrap",
    PAIS: "",
    IMG_SRC: "la_cuesta.png",
  },
  {
    ID: "43",
    PROYECTO: "Estacion",
    TITULO: "Venta de lotes",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Grupo Miterra",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2018",
    TAG: "",
    CATEGORIA: "Landing",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja",
    LINK: "https://estdelcarmen.com.ar/",
    TAG_MOCK: "#Bootstrap",
    PAIS: "",
    IMG_SRC: "estacion_del_carmen.png",
  },
  {
    ID: "45",
    PROYECTO: "Domo",
    TITULO: "Seguridad electrónica",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Domo",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2019",
    TAG: "",
    CATEGORIA: "Landing",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://domoseguridad.com.ar/alarmacomodato/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Domo.png",
  },
  {
    ID: "46",
    PROYECTO: "Domo",
    TITULO: "Seguridad electrónica",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Domo",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2019",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Falta mock",
    PRIORIDAD: "Media",
    LINK: "https://domoseguridad.com.ar/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Domo.png",
  },
  {
    ID: "47",
    PROYECTO: "Kendall",
    TITULO: "Academia de Inglés",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Kendall",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2016",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja",
    LINK: "http://kendallschool.com.ar/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "kendall.png",
  },
  {
    ID: "48",
    PROYECTO: "Suplementos",
    TITULO: "",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "eCommerce",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Suplementos.png",
  },
  {
    ID: "49",
    PROYECTO: "Toog Helados",
    TITULO: "Fábrica de helados",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Toog Helados ",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2019",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "http://toogood.com.ar/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "too_good.png",
  },
  {
    ID: "50",
    PROYECTO: "Everlight",
    TITULO: "Fábrica de mochilas y bolsos",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Freiberg SA",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2018",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja",
    LINK: "http://everlight.com.ar/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "everlight.png",
  },
  {
    ID: "",
    PROYECTO: "Everlight",
    TITULO: "Fábrica de mochilas y bolsos",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Freiberg SA",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "2018",
    TAG: "",
    CATEGORIA: "Landing",
    WEB: "",
    MOBILE: "",
    MOCK: "",
    PRIORIDAD: "Baja",
    LINK: "http://everlight.com.ar/representar.html",
    TAG_MOCK: "#Lead",
    PAIS: "",
    IMG_SRC: "everlight.png",
  },
  {
    ID: "51",
    PROYECTO: "Freiberg",
    TITULO: "Libreria Maorista ",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Freiberg SA",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja",
    LINK: "https://www.freiberg.com.ar/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Freiberg.png",
  },
  {
    ID: "52",
    PROYECTO: "Congreso psico",
    TITULO: "No funciona",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Landing",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "congreso_psico.png",
  },
  {
    ID: "53",
    PROYECTO: "Nimbo",
    TITULO: "No funciona",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Gastón Avila",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://chimpancedigital.com.ar/nimbo/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Nimbo.png",
  },
  {
    ID: "54",
    PROYECTO: "Orden de la merced",
    TITULO: "Escuela Religiosa",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Di Cuore",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja",
    LINK: "https://merced.org.ar/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "orden_de_la_merced.png",
  },
  {
    ID: "55",
    PROYECTO: "Tecnicos",
    TITULO: "No funciona",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "",
  },
  {
    ID: "56",
    PROYECTO: "Coralt",
    TITULO: "No funciona",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Inglobe SRL",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Coralt.png",
  },
  {
    ID: "57",
    PROYECTO: "Meta obra",
    TITULO: "Venta de maquinaria",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Meta Obra",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja Baja",
    LINK: "http://www.metalobra.com/inicio/",
    TAG_MOCK: "#Wordpress",
    PAIS: "",
    IMG_SRC: "metaobra.png",
  },
  {
    ID: "58",
    PROYECTO: "Perikos",
    TITULO: "Panadería ",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja",
    LINK: "http://panaderiasperikos.com.ar/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Perikos.png",
  },
  {
    ID: "59",
    PROYECTO: "Exploradores",
    TITULO: "Sitio web de exploradores",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja Baja",
    LINK: "https://eadb.org.ar",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Exploradores.png",
  },
  {
    ID: "60",
    PROYECTO: "Administracion",
    TITULO: "No funciona",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "baja",
    LINK: "http://chimpance.digital/admingc/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Administracion.png",
  },
  {
    ID: "61",
    PROYECTO: "Escarabajo",
    TITULO: "No funciona",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja Baja",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Escarabajo_kids.png",
  },
  {
    ID: "62",
    PROYECTO: "Spada",
    TITULO: "Video Juego",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Gustavo Sanaria",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://cordobaresistencias.com.ar/",
    TAG_MOCK: "",
    PAIS: "Estados Unidos",
    IMG_SRC: "",
  },
  {
    ID: "63",
    PROYECTO: "CEDAC",
    TITULO: "Centro de estetica",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja",
    LINK: "https://cedacderma.com.ar/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "CEDAC.png",
  },
  {
    ID: "64",
    PROYECTO: "Expo rural",
    TITULO: "No funciona",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Landing",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "rural.png",
  },
  {
    ID: "65",
    PROYECTO: "Claro",
    TITULO: "No funciona",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Landing",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Claro.png",
  },
  {
    ID: "66",
    PROYECTO: "Gobierno abierto",
    TITULO: "No funciona",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Inglobe SRL",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "",
  },
  {
    ID: "67",
    PROYECTO: "Cinergia web",
    TITULO: "Productora audiovisual ",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Cinergia Estudio Creativo",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Alta",
    LINK: "https://cinergiaestudiocreativo.com/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Cinergia.png",
  },
  {
    ID: "68",
    PROYECTO: "Decolores",
    TITULO: "Escuela Montessori",
    SOBRE: "",
    RURO: "",
    CLIENTE: "De Colores ",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Alta",
    LINK: "https://decoloresdc.com/",
    TAG_MOCK: "",
    PAIS: "Estados Unidos",
    IMG_SRC: "De_colores.png",
  },
  {
    ID: "69",
    PROYECTO: "Singulares",
    TITULO: "Empresa de Recursos Humanos",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Cinergia Estudio Creativo",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Alta",
    LINK: "https://singulares.com/",
    TAG_MOCK: "",
    PAIS: "Chile",
    IMG_SRC: "Singulares.png",
  },
  {
    ID: "70",
    PROYECTO: "The weed shool",
    TITULO: "No funciona",
    SOBRE: "",
    RURO: "",
    CLIENTE: "The weed school",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "The_weed_school.png",
  },
  {
    ID: "71",
    PROYECTO: "Orishinal",
    TITULO: "Agencia de Influencers ",
    SOBRE: "",
    RURO: "",
    CLIENTE: "MCDG",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://orishinal.com/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Orishinal.png",
  },
  {
    ID: "73",
    PROYECTO: "Arvan",
    TITULO: "Cursos Online de estética",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Plataforma",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://arvancapacitaciones.com/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Arvan.png",
  },
  {
    ID: "74",
    PROYECTO: "BHI",
    TITULO: "Agencia de viaje mayorista",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Alta",
    LINK: "https://app.bhiviajes.com.ar/home/dashboard",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Bhi_viajes.png",
  },
  {
    ID: "75",
    PROYECTO: "Celina Espada",
    TITULO: "No funciona",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "celina_espada.png",
  },
  {
    ID: "76",
    PROYECTO: "Satelite",
    TITULO: "Empresa de satelites",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Cinergia Estudio Creativo",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Alta",
    LINK: "https://grupoandesat.com/satelite-andesat1/",
    TAG_MOCK: "",
    PAIS: "Perú",
    IMG_SRC: "Andesat.png",
  },
  {
    ID: "78",
    PROYECTO: "Bruno Neff",
    TITULO: "Web profesional ",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Baja",
    LINK: "http://xn--broneff-n2a.ch/",
    TAG_MOCK: "",
    PAIS: "Suiza",
    IMG_SRC: "Bruno_neff.png",
  },
  {
    ID: "79",
    PROYECTO: "Salud y vida",
    TITULO: "No funciona",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "Falta mock",
    PRIORIDAD: "Baja",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "",
  },
  {
    ID: "80",
    PROYECTO: "Ecocampo",
    TITULO: "No funciona",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "",
  },
  {
    ID: "81",
    PROYECTO: "up Lisboa",
    TITULO: "No funciona",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "Falta mock",
    PRIORIDAD: "Baja",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "up_lisboa.png",
  },
  {
    ID: "82",
    PROYECTO: "Torre fluss",
    TITULO: "No funciona",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "Falta mock",
    PRIORIDAD: "Baja",
    LINK: "http://chimpance.digital/torrefluss/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Fluss.png",
  },
  {
    ID: "83",
    PROYECTO: "Vitabiosa",
    TITULO: "Venta de productos dietarios ",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Media",
    LINK: "https://vitabiosa.com.ar/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "vitabiosa.png",
  },
  {
    ID: "84",
    PROYECTO: "Costa Esmelada",
    TITULO: "",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Alta ",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Costa_esmeralda.png",
  },
  {
    ID: "85",
    PROYECTO: "COPA",
    TITULO: "Colegio de Agrimensores ",
    SOBRE: "",
    RURO: "",
    CLIENTE: "COPA SUR",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Alta",
    LINK: "https://copa.org.ar/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "Copa.png",
  },
  {
    ID: "86",
    PROYECTO: "Cuentos Chile",
    TITULO: "",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "",
    PRIORIDAD: "",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "cuentos_chiles.png",
  },
  {
    ID: "87",
    PROYECTO: "Ofarrel",
    TITULO: "Consignataria de hacienda ",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Cinergia Estudio Creativo",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "Listo",
    PRIORIDAD: "Alta",
    LINK: "https://www.ivanofarrell.com.ar/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "O_farrel.png",
  },
  {
    ID: "88",
    PROYECTO: "CRE",
    TITULO: "Resistencias Eléctricas",
    SOBRE: "",
    RURO: "",
    CLIENTE: "CRE SRL",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "",
    PRIORIDAD: "Baja ",
    LINK: "https://cordobaresistencias.com.ar/",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "",
  },
  {
    ID: "89",
    PROYECTO: "Amerian",
    TITULO: "Hotel Amerian",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Inglobe SRL",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "",
    PRIORIDAD: "Media",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "",
  },
  {
    ID: "90",
    PROYECTO: "Popatik",
    TITULO: "Estudio de diseño y comunicación",
    SOBRE: "",
    RURO: "",
    CLIENTE: "Popatik",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Institucional",
    WEB: "",
    MOBILE: "",
    MOCK: "",
    PRIORIDAD: "Media",
    LINK: "https://popatik.com/",
    TAG_MOCK: "",
    PAIS: "Pasí vazco",
    IMG_SRC: "",
  },
  {
    ID: "91",
    PROYECTO: "Paraná Logistica",
    TITULO: "",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "",
    PRIORIDAD: "",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "",
  },
  {
    ID: "92",
    PROYECTO: "Clean see",
    TITULO: "",
    SOBRE: "",
    RURO: "",
    CLIENTE: "",
    DESCRIPCION_DESKTOP: "",
    DESCRIPCION_MOBILE: "",
    AÑO: "",
    TAG: "",
    CATEGORIA: "Otros",
    WEB: "",
    MOBILE: "",
    MOCK: "",
    PRIORIDAD: "",
    LINK: "",
    TAG_MOCK: "",
    PAIS: "",
    IMG_SRC: "",
  },
];

const categories = {};
const getCategories = (categoryArray, categoryName) => {
    categoryArray.forEach(category => {
        if(categories[categoryName]){
          if(!categories[categoryName].includes(category)) categories[categoryName].push(category)
        } else {
          categories[categoryName] = [category]
        }
    })
};

const trasnformGaleryJson = (galeryJson) => {
  galeryJson.forEach((proyect) => {
    proyect.CATEGORIA = proyect.CATEGORIA.split(" ");
    proyect.PROYECTO = proyect.PROYECTO.trim()
    proyect.TAG = proyect.TAG.split(" ");
    proyect.TAG_MOCK = proyect.TAG_MOCK.split(" ");
    /* aca puedo ir agregando las categorias que necesito y sus titulos */
    getCategories(proyect.CATEGORIA, "Tipos de Web");
    getCategories(proyect.CATEGORIA, "Lenguajes");
    getCategories(proyect.CATEGORIA, "Otros");

  });
  return galeryJson;
};


export const sortedJson = trasnformGaleryJson(galeryProyects);



export const allCategories = categories




